[book]
authors = ["RM"]
language = "en"
multilingual = false
src = "src"
title = "Mdbook Template"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["./src/theme/heti.min.css"]




